import React, { useState, useEffect } from 'react';
import { X } from 'lucide-react';
import { AssetResponse } from './AssetTable';

interface Category {
  id: number;
  name: string;
}

interface Department {
  id: number;
  name: string;
}

interface AssetFormModalProps {
  isOpen: boolean;
  mode: 'add' | 'edit';
  initialData: AssetResponse | null;
  categories: Category[];
  departments: Department[];
  onClose: () => void;
  onSave: (assetData: any) => void;
}

export const AssetFormModal: React.FC<AssetFormModalProps> = ({ 
  isOpen, mode, initialData, categories, departments, onClose, onSave 
}) => {
  const [formData, setFormData] = useState<any>({
    name: '',
    category_id: '',
    status: 'available',
    location: '',
    serial_number: '',
    acquisition_date: '',
    acquisition_cost: '',
    condition: 'good',
    department_id: '',
    is_shared: false
  });

  useEffect(() => {
    if (isOpen) {
      if (mode === 'edit' && initialData) {
        setFormData({
          name: initialData.name,
          category_id: initialData.category_id,
          status: initialData.status,
          location: initialData.location,
          serial_number: initialData.serial_number || '',
          acquisition_date: initialData.acquisition_date || '',
          acquisition_cost: initialData.acquisition_cost || '',
          condition: initialData.condition || 'good',
          department_id: initialData.department_id || '',
          is_shared: initialData.is_shared || false
        });
      } else {
        setFormData({ 
          name: '', category_id: categories.length > 0 ? categories[0].id : '', 
          status: 'available', location: '', serial_number: '', 
          acquisition_date: new Date().toISOString().split('T')[0], 
          acquisition_cost: '', condition: 'good', department_id: '', is_shared: false
        });
      }
    }
  }, [isOpen, mode, initialData, categories]);

  if (!isOpen) return null;

  const handleSave = () => {
    if (!formData.name || !formData.category_id || !formData.status || !formData.location || !formData.acquisition_cost || !formData.acquisition_date || !formData.serial_number) {
      alert("Please fill in all required fields (Name, Category, Status, Location, Date, Cost, Serial).");
      return;
    }
    
    const payload = {
      ...formData,
      category_id: Number(formData.category_id),
      acquisition_cost: Number(formData.acquisition_cost),
      department_id: formData.department_id ? Number(formData.department_id) : null,
    };
    onSave(payload);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 font-sans">
      <div 
        className="absolute inset-0 bg-black/50 dark:bg-black/80 backdrop-blur-sm animate-in fade-in duration-200"
        onClick={onClose}
      />
      <div 
        className="relative w-full max-w-lg bg-surface border border-border rounded-2xl shadow-2xl overflow-hidden transition-colors duration-300 flex flex-col max-h-[90vh] animate-in zoom-in-95 duration-200"
      >
        <div className="flex items-center justify-between p-6 border-b border-border shrink-0">
          <h2 className="text-lg font-semibold tracking-tight text-foreground">
            {mode === 'add' ? 'Register New Asset' : 'Edit Asset'}
          </h2>
          <button onClick={onClose} className="text-muted hover:text-foreground transition-colors">
            <X className="h-5 w-5" />
          </button>
        </div>
        
        <div className="p-6 space-y-5 overflow-y-auto">
          {/* Note: Tag is auto-generated by the backend so we don't include it in creation */}
          
          <div className="grid grid-cols-2 gap-4">
            <div className="col-span-2">
              <label className="block text-[13px] font-medium text-muted mb-2">Asset Name *</label>
              <input 
                type="text" 
                value={formData.name}
                onChange={(e) => setFormData({...formData, name: e.target.value})}
                placeholder="e.g. Dell Laptop"
                className="w-full px-4 py-2.5 bg-background border border-border rounded-xl text-[13px] text-foreground placeholder:text-muted focus:outline-none focus:border-primary transition-colors"
              />
            </div>
          </div>
          
          <div className="grid grid-cols-2 gap-4">
            <div className="col-span-2 sm:col-span-1">
              <label className="block text-[13px] font-medium text-muted mb-2">Category *</label>
              <select 
                value={formData.category_id}
                onChange={(e) => setFormData({...formData, category_id: e.target.value})}
                className="w-full px-4 py-2.5 bg-background border border-border rounded-xl text-[13px] text-foreground focus:outline-none focus:border-primary appearance-none cursor-pointer transition-colors"
              >
                <option value="">Select Category</option>
                {categories.map(c => (
                   <option key={c.id} value={c.id}>{c.name}</option>
                ))}
              </select>
            </div>
            <div className="col-span-2 sm:col-span-1">
              <label className="block text-[13px] font-medium text-muted mb-2">Status *</label>
              <select 
                value={formData.status}
                onChange={(e) => setFormData({...formData, status: e.target.value})}
                disabled={mode === 'add'} // Status defaults to available on add
                className="w-full px-4 py-2.5 bg-background border border-border rounded-xl text-[13px] text-foreground focus:outline-none focus:border-primary appearance-none cursor-pointer transition-colors disabled:opacity-60"
              >
                <option value="available">Available</option>
                <option value="allocated">Allocated</option>
                <option value="reserved">Reserved</option>
                <option value="under_maintenance">Under Maintenance</option>
                <option value="lost">Lost</option>
                <option value="retired">Retired</option>
                <option value="disposed">Disposed</option>
              </select>
              {mode === 'add' && <p className="text-[10px] text-muted mt-1">New assets start as Available</p>}
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="col-span-2 sm:col-span-1">
              <label className="block text-[13px] font-medium text-muted mb-2">Location *</label>
              <input 
                type="text" 
                value={formData.location}
                onChange={(e) => setFormData({...formData, location: e.target.value})}
                placeholder="e.g. Bengaluru HQ"
                className="w-full px-4 py-2.5 bg-background border border-border rounded-xl text-[13px] text-foreground placeholder:text-muted focus:outline-none focus:border-primary transition-colors"
              />
            </div>
            <div className="col-span-2 sm:col-span-1">
              <label className="block text-[13px] font-medium text-muted mb-2">Department</label>
              <select 
                value={formData.department_id}
                onChange={(e) => setFormData({...formData, department_id: e.target.value})}
                className="w-full px-4 py-2.5 bg-background border border-border rounded-xl text-[13px] text-foreground focus:outline-none focus:border-primary appearance-none cursor-pointer transition-colors"
              >
                <option value="">None / Company-wide</option>
                {departments.map(d => (
                   <option key={d.id} value={d.id}>{d.name}</option>
                ))}
              </select>
            </div>
          </div>
          
          <div className="grid grid-cols-2 gap-4">
            <div className="col-span-2 sm:col-span-1">
              <label className="block text-[13px] font-medium text-muted mb-2">Serial Number *</label>
              <input 
                type="text" 
                value={formData.serial_number}
                onChange={(e) => setFormData({...formData, serial_number: e.target.value})}
                placeholder="e.g. SN-10293"
                className="w-full px-4 py-2.5 bg-background border border-border rounded-xl text-[13px] text-foreground placeholder:text-muted focus:outline-none focus:border-primary font-mono transition-colors"
              />
            </div>
            <div className="col-span-2 sm:col-span-1">
              <label className="block text-[13px] font-medium text-muted mb-2">Condition</label>
              <select 
                value={formData.condition}
                onChange={(e) => setFormData({...formData, condition: e.target.value})}
                className="w-full px-4 py-2.5 bg-background border border-border rounded-xl text-[13px] text-foreground focus:outline-none focus:border-primary appearance-none cursor-pointer transition-colors"
              >
                <option value="new">New</option>
                <option value="good">Good</option>
                <option value="fair">Fair</option>
                <option value="poor">Poor</option>
              </select>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="col-span-2 sm:col-span-1">
              <label className="block text-[13px] font-medium text-muted mb-2">Acquisition Date *</label>
              <input 
                type="date" 
                value={formData.acquisition_date}
                onChange={(e) => setFormData({...formData, acquisition_date: e.target.value})}
                className="w-full px-4 py-2.5 bg-background border border-border rounded-xl text-[13px] text-foreground focus:outline-none focus:border-primary transition-colors"
              />
            </div>
            <div className="col-span-2 sm:col-span-1">
              <label className="block text-[13px] font-medium text-muted mb-2">Acquisition Cost *</label>
              <input 
                type="number" 
                value={formData.acquisition_cost}
                onChange={(e) => setFormData({...formData, acquisition_cost: e.target.value})}
                placeholder="e.g. 1200"
                className="w-full px-4 py-2.5 bg-background border border-border rounded-xl text-[13px] text-foreground placeholder:text-muted focus:outline-none focus:border-primary transition-colors"
              />
            </div>
          </div>

          <div className="flex items-center justify-between bg-surface-alt p-4 rounded-xl border border-border">
            <div>
              <p className="text-[13px] font-medium text-foreground">Shared / Bookable</p>
              <p className="text-[11px] text-muted mt-0.5">Allow this asset to be booked by others</p>
            </div>
            <label className="relative inline-flex items-center cursor-pointer">
              <input 
                type="checkbox" 
                checked={formData.is_shared}
                onChange={(e) => setFormData({...formData, is_shared: e.target.checked})}
                className="sr-only peer" 
              />
              <div className="w-11 h-6 bg-border-strong peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-text-primary"></div>
            </label>
          </div>
        </div>
        
        <div className="p-6 border-t border-border flex justify-end gap-3 bg-surface-alt transition-colors duration-300 shrink-0">
          <button 
            onClick={onClose}
            className="px-5 py-2 text-[13px] font-medium text-muted hover:text-foreground transition-colors"
          >
            Cancel
          </button>
          <button 
            onClick={handleSave}
            className="px-5 py-2 text-[13px] font-medium  bg-btn-bg hover:bg-btn-hover text-btn-text shadow-sm hover:opacity-90 rounded-full transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {mode === 'add' ? 'Register' : 'Save Changes'}
          </button>
        </div>
      </div>
    </div>
  );
};
